name: CI
on: [push, pull_request]

jobs:
  test:
    # cannot use latest to check older OTP versions, see:
    # https://github.com/erlef/setup-beam/issues/161#issuecomment-1336129218
    runs-on: ubuntu-20.04
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    env:
      MIX_ENV: test
    strategy:
      matrix:
        include:
          - elixir: "1.12"
            otp: "23.3"
            testArgs: "--exclude=lts_only"
          - elixir: "1.14"
            otp: "25.3"
            testArgs: "--exclude=lts_only"
          - elixir: "1.15"
            otp: "26.0"
            testArgs: "--exclude=lts_only"
          - elixir: "1.16"
            otp: "26.2"
            testArgs: "--exclude=lts_only"
          - elixir: "1.17.2"
            otp: "27.0"
            testArgs: "--exclude=lts_only"
          - elixir: "1.18.4"
            otp: "27.0"
            testArgs: "--exclude=lts_only"
          - elixir: "1.19.0-rc.1"
            otp: "28.1"
            testArgs: ""
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: mix deps.get
      - name: Check compile warnings
        run: mix compile --warnings-as-errors
      # TODO add dialyzer?
      - name: Unit tests
        run: mix test.unit ${{ matrix.testArgs }}
      - name: Property-based tests
        run: PROP_TEST_RUNTIME=30000 mix test.prop ${{ matrix.testArgs }}

  format:
    runs-on: ubuntu-latest
    name: Format (Elixir ${{matrix.elixir}})
    strategy:
      matrix:
        include:
          - elixir: "1.18"
            otp: "27.0"
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: mix deps.get
      - name: Check format
        run: mix format --check-formatted
